services:
  app:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=https://dvnzjlkbldfssegeoaxj.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2bnpqbGtibGRmc3NlZ2VvYXhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzAzMDEsImV4cCI6MjA2Mzg0NjMwMX0.pOZeKsQtk147WkpWDBEf9gwYsQoMJ1s6Fv8ZshoVRf4
    command: sh -c "npm ci && npm run dev"
