version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # Evita a sincronização de node_modules entre host e container
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # Comando para permitir o hot-reload
    command: sh -c "npm run dev -- -p 3000"
